### ISSUE TITLE
not working on Lenovo Yoga 910

### ISSUE THREAD

**Issue by focmb** [okeri/ideapad-hacks#2]
I tried this on my Lenovo Yoga 910 with Manjaro linux. After **make** and **insmod** nothing happend. The find command gave me no feedback, **fn_lock** was not found.

**Comment by okeri** [comment]
Hi, could you please provide output for both **make** and **insmod** command& The output of insmod could be optained by typing **dmesg | tail**

**Comment by focmb** [comment]
Output of make:

`make -C /lib/modules/`uname -r`/build M=$PWD
make[1]: Verzeichnis „/usr/lib/modules/4.15.18-2-MANJARO/build“ wird betreten
  CC [M]  /home/leitzke/Downloads/ideapad-hacks/ideapad-hacks.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/leitzke/Downloads/ideapad-hacks/ideapad-hacks.mod.o
  LD [M]  /home/leitzke/Downloads/ideapad-hacks/ideapad-hacks.ko
make[1]: Verzeichnis „/usr/lib/modules/4.15.18-2-MANJARO/build“ wird verlassen`

**Comment by okeri** [comment]
Well, module compiled succefully, but output of dmesg | tail is ambigous.
Please make sure, you have unloaded ideapad_laptop kernel module( e.g. **sudo rmmod ideapad_laptop** or **modpropbe -r ideapad_laptop**)  before insmod ideapad-hacks.ko
If if does not help, please copy+paste full dmesg log after insmod ideapad-hacks.ko

**Comment by focmb** [comment]
I cleaned the dmesg with sudo dmesg -C and removed the kernel modul. After that I did a sudo insmod ideapad-hack.ko but the dmesg is still empty, there are no dmes entries

**Comment by okeri** [comment]
It seems everything is ok. So what **lsmod** shows ? Is there present ideapad-hacks module and missing ideapad_laptop. (l**smod | grep ideapad**)

**Comment by focmb** [comment]
Output of lsmod:

`ideapad_hacks          16384  0
ideapad_laptop         36864  0
sparse_keymap          16384  1 ideapad_laptop
rfkill                 28672  9 bluetooth,ideapad_laptop,cfg80211
wmi                    28672  3 wmi_bmof,intel_wmi_thunderbolt,ideapad_laptop
i8042                  32768  1 ideapad_laptop
                                                 `

**Comment by okeri** [comment]
As i already told before, the issue is incompatibility of ideapad_laptop and ideapad-hacks modules.
ideapad-hacks is out-of-mainline module, and it could be loaded via insmod, not modprobe. also ideapad-hacks must be loaded while ideapad_laptops was not present in kernel-space.
it seems the total solution of this issue for you is 3 simple steps:
**rmmod ideapad-hacks**;
**rmmod ideapad-laptop**;
**insmod <path to ideapad-hacks.ko>**;
and continue with **find /sys -name fn_lock**" from README

**Comment by focmb** [comment]
The ideapad_laptop module was blacklistet and not loaded. Now your module is working. I will test if it survives a reboot. Otherwise I will load it with a script on startup

**Comment by okeri** [comment]
Actually there is no need to keep module loaded. While fn_lock setting is set it keep working after reboot even using any other OS.
