### ISSUE TITLE
not working on Ubuntu 18.04

### ISSUE THREAD

**Issue by ec1oud** [okeri/ideapad-hacks#3]
kernel version is 4.15.0-20-generic

I can insert the module, but I'm not finding a fn_lock file anywhere in /sys.  There's no error output either, only this:

[   43.884323] ideapad_hacks: module verification failed: signature and/or required key missing - tainting kernel

```
$ ll /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/
total 0
drwxr-xr-x 5 root root    0 2018-05-27 12:59 ./
drwxr-xr-x 8 root root    0 2018-05-27 12:33 ../
-rw-r--r-- 1 root root 4096 2018-05-27 12:59 camera_power
-rw-r--r-- 1 root root 4096 2018-05-27 12:59 conservation_mode
lrwxrwxrwx 1 root root    0 2018-05-27 12:33 driver -> ../../../../../bus/platform/drivers/ideapad_acpi/
-rw-r--r-- 1 root root 4096 2018-05-27 12:59 driver_override
-rw-r--r-- 1 root root 4096 2018-05-27 12:59 fan_mode
lrwxrwxrwx 1 root root    0 2018-05-27 12:59 firmware_node -> ../../../../LNXSYSTM:00/LNXSYBUS:00/PNP0A08:00/device:19/PNP0C09:00/VPC2004:00/
drwxr-xr-x 3 root root    0 2018-05-27 12:33 input/
-r--r--r-- 1 root root 4096 2018-05-27 12:59 modalias
drwxr-xr-x 2 root root    0 2018-05-27 12:34 power/
drwxr-xr-x 4 root root    0 2018-05-27 12:33 rfkill/
lrwxrwxrwx 1 root root    0 2018-05-27 12:33 subsystem -> ../../../../../bus/platform/
-r--r--r-- 1 root root 4096 2018-05-27 12:59 touchpad
-rw-r--r-- 1 root root 4096 2018-05-27 12:33 uevent
```

**Comment by okeri** [comment]
You have already ideapad_laptop module loaded. To use ideapad-hacks you must unload or blacklist ideapad_laptop first.

**Comment by ec1oud** [comment]
Yep unloading ideapad_laptop helps.  Now /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/fn_lock exists, and I can read it, but can't write to it (permission denied, even though I used sudo).

It turned out that the setting was missing from Vantage because I needed to do a BIOS upgrade; after doing that, I was at least able to get the function-lock reversed in Windows, and it does seem to be persistent (affects behavior in Linux too), so now I don't need this module as much as I thought I did.

**Comment by okeri** [comment]
This is very strange behavoir. Module checks if firmware supported required acpi functionality.
In case of succefull detection fn_lock has 0644 attr, otherwise - 000. This means technically if you can read sysfs value (even from user), you can modify it with root access.

**Comment by ar-g** [comment]
By some reason it doesn't work through `sudo echo 0> /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/fn_lock 

zsh: permission denied: /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/fn_lock
`

but it works through sublime

`sudo subl /sys/devices/pci0000:00/0000:00:1f.0/PNP0C09:00/VPC2004:00/fn_lock`

probably some minor changes in syntaxis of Ubuntu 18.04 or smth
